version: '3.0'

services:
  backend:
    container_name: nestjs_api
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app/backend
      - ./:/usr/src/app/backend/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: database-1.c0ak93sweexj.eu-central-1.rds.amazonaws.com
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
